import Head from "next/head";
import { useState } from "react";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Skill from "../components/Skill";
import Project from "../components/Project";
import About from "../components/About";
import Contact from "../components/Contact";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-[#eee] px-10 dark:bg-[#222] md:px-20 2xl:px-56 selection:bg-[#aaaaaaa5] dark:selection:bg-[#eeeeee31]">
        <section className="min-h-screen">
          <Navbar setDarkMode={setDarkMode} darkMode={darkMode} />
          <Hero />
        </section>
        <section className="mt-20">
          <About />
        </section>
        <section className="my-10 mt-28">
          <Skill />
        </section>
        <section className="py-10 mt-20">
          <Project />
        </section>
        <section className="py-10">
          <Contact />
        </section>
      </main>
    </div>
  );
}
